FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod gosum ./
RUN go mod download

COPY . . 

RUN CGO_ENABLED=0 GOOS=linux \
    go build -ldflags="-s -w"\
    -o toolhub-client \
    ./cmd/client


FROM alpine:3.22

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /app/toolhub-client .


ENTRYPOINT ["./toolhub-client"]
