services:
  postgres:
    image: postgres:17-alpine
    container_name: toolhub-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    
  server:
    build:
      context: ./server
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build:      
      context: ./client
    depends_on:
      postgres:
        condition: service_healthy  
volumes:
  postgres_data:

